version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    container_name: db_project
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5435:5432
  redis:
    image: redis:5.0.6
    container_name: redis
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: django
#    command:  gunicorn wsgi:application --bind 0.0.0.0:8000
    command:  bash -c "python /usr/src/django_project/stones/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/django_project/
    depends_on:
      - db
      - redis
    env_file:
      - .env
    entrypoint: /usr/src/django_project/docker/entrypoint.sh
    ports:
      - "8000:8000"
#  nginx:
#    image: nginx:1.21.3-alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - static_value:/var/html/static/
#    depends_on:
#      - web

volumes:
  postgres_data: